### ISSUE TITLE
Rebuild corrplot as a userplot

### ISSUE THREAD

**Issue by tbreloff** [JuliaPlots/PlotRecipes.jl#1]
... and remove it from MLPlots.

**Comment by tbreloff** [comment]
So much better.

```julia
using PlotRecipes
M = randn(1000,4)
M[:,2] += 0.8sqrt(abs(M[:,1])) - 0.5M[:,3] + 5
M[:,3] -= 0.7M[:,1].^2 + 2

corrplot(M, label = ["x$i" for i=1:4])
```

![tmp](https://cloud.githubusercontent.com/assets/933338/16030833/3c84e6bc-31c3-11e6-9a04-4cee531440a4.png)

**Comment by mauro3** [comment]
I played around with that recipe a bit, let me know if of interest. Plotting above data with
```
cornerplot(M, label = ["x$i" for i=1:4], compact=true)
```
![cor1](https://cloud.githubusercontent.com/assets/4098145/16147156/dc7d8d34-3481-11e6-82a9-60d7a9c29734.png)
and
```
cornerplot(M, label = ["x$i" for i=1:4])
```
![cor2](https://cloud.githubusercontent.com/assets/4098145/16147170/e90fcbe8-3481-11e6-9e75-8bf3785022ea.png)

**Comment by Evizero** [comment]
@tbreloff what is it with you and really huge markers in scatterplots :) ?

**Comment by tbreloff** [comment]
Very cool mauro!

**Comment by tbreloff** [comment]
@mauro3 Any interest to submit a PR for cornerplot?
