### ISSUE TITLE
Optional PlotRecipes dependency on Shapefile produces precompilation error

### ISSUE THREAD

**Issue by jiahao** [JuliaPlots/PlotRecipes.jl#10]
```jl
using Shapefile, PlotRecipes
```

currently produces an error:

```jl
INFO: Precompiling module PlotRecipes.
WARNING: Module Shapefile with uuid 106384620846421 is missing from the cache.
This may mean module Shapefile does not support precompilation but is imported by a module that does.
ERROR: LoadError: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
...
```

The reason is because `Shapefile` currently does not support precompilation.

**Comment by jiahao** [comment]
Strictly speaking, the correct solution is to disallow precompilation, at least when the `ShapeFile` module is loaded. However, it seems easier to simply turn on precompilation for `ShapeFile.jl`.

**Comment by tbreloff** [comment]
https://github.com/JuliaPlots/PlotRecipes.jl/commit/ef0a67e35568b4229b3d47a3d32abd677f2718a3

**Comment by mkborregaard** [comment]
I'm guessing this can be closed.
