### ISSUE TITLE
arcdiagram broken in Julia 0.5

### ISSUE THREAD

**Issue by diegozea** [JuliaPlots/PlotRecipes.jl#13]
```
julia> using PlotRecipes

julia> plot(
           arcdiagram(['A','A','A','B'], ['B','C','D','A'], [1,2,3,1]),
           arcdiagram(rand(10), rand(10)),
           arcdiagram(rand(10), rand(10), rand(10)),
           arcdiagram(rand(10,10)),
           arcdiagram(Symmetric(rand(10,10))),
           arcdiagram(sparse([0 0 0; 1 1 0; 1 1 1]))
       )
ERROR: ArgumentError: invalid index: 0.956756381239916
 in getindex(::Array{Tuple{Float64,Float64},1}, ::Float64) at ./array.jl:386
 in macro expansion at /home/dzea/.julia/v0.5/PlotRecipes/src/graphs.jl:423 [inlined]
 in macro expansion at /home/dzea/.julia/v0.5/RecipesBase/src/RecipesBase.jl:276 [inlined]
 in macro expansion at /home/dzea/.julia/v0.5/PlotRecipes/src/graphs.jl:421 [inlined]
 in apply_recipe(::Dict{Symbol,Any}, ::PlotRecipes.ArcDiagram) at /home/dzea/.julia/v0.5/RecipesBase/src/RecipesBase.jl:238
 in _process_userrecipes(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Tuple{PlotRecipes.ArcDiagram}) at /home/dzea/.julia/v0.5/Plots/src/pipeline.jl:73
 in _plot!(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Tuple{PlotRecipes.ArcDiagram}) at /home/dzea/.julia/v0.5/Plots/src/plot.jl:171
 in #arcdiagram#35(::Array{Any,1}, ::Function, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /home/dzea/.julia/v0.5/Plots/src/recipes.jl:37
 in arcdiagram(::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /home/dzea/.julia/v0.5/Plots/src/recipes.jl:37
```

**Comment by jpsamaroo** [comment]
I can reproduce this with Julia 0.5.1, PlotRecipes commit `033ae43`. After printing out the variables `vertices`, `i`, `j`, and `value` (in that order), this is the output I get from running the same example:

```
Dict('A'=>1,'B'=>2,'C'=>3,'D'=>4)
A
B
1
Dict('A'=>1,'B'=>2,'C'=>3,'D'=>4)
A
C
2
Dict('A'=>1,'B'=>2,'C'=>3,'D'=>4)
A
D
3
Dict('A'=>1,'B'=>2,'C'=>3,'D'=>4)
B
A
1
Tuple{Float64,Float64}[(0.888238,0.888238),(0.95867,0.95867),(0.319894,0.319894),(0.235685,0.235685),(0.892361,0.892361),(0.577999,0.577999),(0.478079,0.478079),(0.902876,0.902876),(0.829184,0.829184),(0.867253,0.867253),(0.845176,0.845176),(0.090373,0.090373),(0.490373,0.490373),(0.600038,0.600038),(0.990853,0.990853),(0.899903,0.899903),(0.56016,0.56016),(0.858868,0.858868),(0.620017,0.620017),(0.749433,0.749433)]
0.888238129830295
0.8451761629445809
1.0
```

It appears that `vertices` suddenly changes from a `Dict` to a vector of `Tuple`, and `i` and `j` change to `Float64` values. Given the size of the tuple vector and the random values, I would assume that it somehow derives from the calls to `rand()` that follow. I'm not exactly sure what's causing this though, as this is my first day using the entire Plots ecosystem. Any ideas?

**Comment by diegozea** [comment]
https://github.com/JuliaPlots/PlotRecipes.jl/pull/30 should solved this, however I just found the following error: 

![image](https://user-images.githubusercontent.com/2822757/29843545-91421f3a-8d0c-11e7-8758-6999cb2cde62.png)

**Comment by diegozea** [comment]
Maybe https://github.com/JuliaPlots/PlotRecipes.jl/pull/34 is related to this problem (?)

**Comment by mkborregaard** [comment]
I get this on master:
<img width="564" alt="skaermbillede 2017-08-30 kl 00 08 15" src="https://user-images.githubusercontent.com/8429802/29846511-77d737be-8d17-11e7-8ab4-30f3fa4c7ca0.png">

**Comment by mkborregaard** [comment]
What's your Pkg.status?

**Comment by diegozea** [comment]
The problem is using PlotRecipes 0.2.0 on Julia 0.5.2

**Comment by mkborregaard** [comment]
Yeah, you need julia 0.6 to work on the current version of PlotRecipes.

**Comment by diegozea** [comment]
I have a lot of code that I haven't finished to port to a newer Julia version. Never mind, It's not a problem then.
