### ISSUE TITLE
marginalhist doesn't support DataFrames 

### ISSUE THREAD

**Issue by diegozea** [JuliaPlots/PlotRecipes.jl#4]
Hi!

`marginalhist(iris,:PetalLength,:PetalWidth)` gives the following error:

```julia 
LoadError: Marginal Histograms should be given two vectors.  Got: Tuple{DataFrames.DataFrame,Symbol,Symbol}
while loading In[76], in expression starting on line 1

 in error at ./error.jl:21
 [inlined code] from /home/dzea/.julia/v0.4/PlotRecipes/src/hists.jl:5
 in __apply_recipe#156__ at /home/dzea/.julia/v0.4/RecipesBase/src/RecipesBase.jl:235
 in _plot! at /home/dzea/.julia/v0.4/Plots/src/plot.jl:256
 in marginalhist at /home/dzea/.julia/v0.4/Plots/src/recipes.jl:42
```

Best,

**Comment by tbreloff** [comment]
Thanks for posting the issue.  This it a design decision that I've been struggling over, and is a bit of a "chicken and egg" problem.  The question is... how much processing do we want to automatically do before getting to the callback?  In some cases you might want the data to be fully processed (for example you can take in vectors, but you wish matrices to be sliced over columns first).  In other cases you want to get the callback before processing (for example in GroupHist you want all the data at once to be able to compute shared histogram edges).

This is similar to series recipes, except that in this case you're building subplots and many series, so I'm not sure that a series recipe is the right concept.

Part of me thinks that we need another type of recipe, that is processed between type recipes and layout/subplot setup.  You'd get fully processed input data, but still the default attribute values would be unset and you can setup the layout, etc.  Then we can still keep the "user recipes" which take in unprocessed input data when you want that.

Thoughts?

**Comment by tbreloff** [comment]
> Part of me thinks that we need another type of recipe, that is processed between type recipes and layout/subplot setup. 

I did this a few weeks ago, and transitioned marginalhist to be a plot recipe.

```julia
using PlotRecipes,RDatasets; iris = dataset("datasets","iris");
marginalhist(iris,:PetalLength,:PetalWidth)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/16709018/81c4da34-45d2-11e6-9e08-bb557541e144.png)

I just pushed up a few fixes so you'll want the Plots `tb_colors` and PlotRecipes `master` for this to work right now.
